{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ladysnake",
    "module": "locki",
    "version": "0.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "locki-0.14.0.jar",
          "url": "locki-0.14.0.jar",
          "size": 69673,
          "sha512": "40e71bfb72e2241c099e332c3f18ff2ee772f65dcb9ba8f47471a0aaf6941421d63d55f5d3dd690be2cee01223b84e5210b30e883eeff1e7f76f5afb31dfcb94",
          "sha256": "9fd873eb69a4b2bcab3cd986a3fe3f7a4fa85ba5be392db0a900aec1eb61a403",
          "sha1": "405343fc435a878e140c5465cb5af1739f9ffcbf",
          "md5": "a6aaf6a380626c755f03801871163d7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.110.0+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.lucko",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "locki-0.14.0.jar",
          "url": "locki-0.14.0.jar",
          "size": 69673,
          "sha512": "40e71bfb72e2241c099e332c3f18ff2ee772f65dcb9ba8f47471a0aaf6941421d63d55f5d3dd690be2cee01223b84e5210b30e883eeff1e7f76f5afb31dfcb94",
          "sha256": "9fd873eb69a4b2bcab3cd986a3fe3f7a4fa85ba5be392db0a900aec1eb61a403",
          "sha1": "405343fc435a878e140c5465cb5af1739f9ffcbf",
          "md5": "a6aaf6a380626c755f03801871163d7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "locki-0.14.0-sources.jar",
          "url": "locki-0.14.0-sources.jar",
          "size": 56700,
          "sha512": "a42381d55426b3180467aab52840949ca62a7d1d6e684a1c6f3de61e70c49213ec91d4a0358f3ea014ee12de88c73651b611a3a6fe9a0e928a5e40c9a3bb0a20",
          "sha256": "063e74cd6adbe03fcedb63155e230e7b83e4eee10881da3c14c46951484a47bd",
          "sha1": "c5d6ef72820076b98da49de40f8ae691d91f5f47",
          "md5": "98160bf25381ccd4f007cfa976989caa"
        }
      ]
    }
  ]
}
