[versions]
acu = "3.3.1"
aea = "1.7.4+1.20.0"
amecs = "1.1.5+mc21w16a"
autoconfig = "3.2.2"
apoli = "2.9.0"
backslot = "3476614"
betterGraves = "0.4.0"
bewitchment = "5205373" # v1.18-9
biomeMakeover = "3634309" # v1.18.1-1.4.4
bumblezone = "3646901" # v4.3.1
calio = "1.11.0"
collective = "5378112" # 7.61
eldritchMobs = "v1.12.6"
fallflyinglib = "3.0.0-beta.2"
flk = "1.6.0+kotlin.1.5.0"
golemsGalore = "3328376" # v1.0.0+mc1.17
kano="0.4.1"
libgui = "3.3.5+1.16.5"
malum="5441759"
midnightlib="1.4.1-fabric"
mobz = "3498091"
omegaConfig = "1.2.1-1.18.1"
origins = "1.10.0"
patchouli = "1.20.1-84-FABRIC"
pehkui = "3.7.7"
reach = "2.1.1"
shea = "1.2.0"
snowmercy = "2.0.1"
somnus = "0.0.14-1.17.1"
structurized = "1.4.0+1.18"
trinkets = "3.7.2"
wood = "7.0.3"

[libraries]
apoli =         { group = "com.github.apace100",     name = "apoli", version.ref = "apoli" }
additionalEntityAttributes = { group = "maven.modrinth", name = "AdditionalEntityAttributes", version.ref = "aea" }
betterGraves =  { group = "io.github.CerulanLumina", name = "better-graves", version.ref = "betterGraves"}
bewitchment =   { group = "curse.maven",             name = "bewitchment-394915", version.ref = "bewitchment"}
biomeMakeover = { group = "curse.maven",             name = "biome-makeover-412182", version.ref = "biomeMakeover" }
bumblezone =    { group = "curse.maven",             name = "the-bumblezone-fabric-363949", version.ref = "bumblezone" }
calio =         { group = "com.github.apace100",     name = "calio", version.ref = "calio" }
collective =    { group = "curse.maven", name = "collective-342584", version.ref="collective"}
eldritchMobs =  { group = "maven.modrinth",   name = "eldritch-mobs", version.ref = "eldritchMobs" }
flk =           { group = "net.fabricmc",            name = "fabric-language-kotlin", version.ref = "flk" }
golemsGalore =  { group = "curse.maven",             name = "golems-galore-387197", version.ref = "golemsGalore" }
libgui =        { group = "io.github.cottonmc",      name = "LibGui", version.ref = "libgui" }
malum =         { group = "curse.maven", name = "malum-484064", version.ref = "malum"}
midnightlib =   { module = "maven.modrinth:midnightlib", version.ref = "midnightlib"}
mobz =          { group = "curse.maven",             name = "mobz-336554", version.ref = "mobz" }
omegaConfig =   { group = "com.github.Draylar.omega-config", name = "omega-config-base", version.ref = "omegaConfig" }
origins =       { group = "maven.modrinth",     name = "origins", version.ref = "origins" }
patchouli =     { group = "vazkii.patchouli",        name = "Patchouli", version.ref = "patchouli" }
pehkui =        { module= "com.github.Virtuoel:Pehkui", version.ref = "pehkui" }
kano_config =   { module= "com.github.Virtuoel:KanosConfig", version.ref = "kano"}
snowmercy =     { module = "io.github.ladysnake:Snow-Mercy", version.ref = "snowmercy" }
stepHeightEntityAttributes = { module = "com.github.emilyploszaj:step-height-entity-attribute", version.ref = "shea" }
structurized =  { module = "com.github.Frqnny:structurized", version.ref = "structurized" }
trinkets =      { module = "dev.emi:trinkets", version.ref = "trinkets" }
woodApi =       { module = "com.terraformersmc.terraform-api:terraform-wood-api-v1", version.ref = "wood" }

[bundles]
bewitchment = ["bewitchment", "stepHeightEntityAttributes", "patchouli", "pehkui", "kano_config", "midnightlib", "trinkets", "woodApi"]
golemsGalore = ["golemsGalore", "structurized"]
origins = ["apoli", "calio", "origins"]
